language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-google-google_play_services
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-23
  licenses:
    - android-sdk-license-.+

before_script:
  - sudo service postgresql stop || true
  - sudo service mysql stop || true
  - sudo service memcached stop || true
  - sudo service bootlogd stop || true
  - sudo service elasticsearch stop || true
  - sudo service mongodb stop || true
  - sudo service neo4j stop || true
  - sudo service cassandra stop || true
  - sudo service riak stop || true
  - sudo service rsync stop || true
  - sudo service x11-common stop || true

  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install
  - openssl aes-256-cbc -K $encrypted_3f126342b36d_key -iv $encrypted_3f126342b36d_iv -in signing.jks.enc -out signing.jks -d
  - openssl aes-256-cbc -K $encrypted_3f126342b36d_key -iv $encrypted_3f126342b36d_iv -in signing.properties.enc -out signing.properties -d

deploy:
  provider: releases
  api_key:
    secure: "yYRPew+sN9gEqv27bUeD7IN/Xd1dtarL/JyETlC2Nw21fCUIKkvchklHflUqtMYbtOU/EIBqA1iQFk5NK+m5T6FiCj4WKi7c+mCs6KacC+Q0smr+9xDKrmRHYufjrY8O4F7NJaoZv+d6kg3+5Bdsa84UvvwfzGmIyVd6YX3CfDrr8vZRbVOiMBodl9sMlIIoMybULpIiQp7ZT2/TE+ytCWylToBAPQdD7HB1Cgqa63Ohyb6nrUjDA2dDz5bWe3crAUUOFETJNSbXWYSxzlx1sYrc1k2pvyyBOvRzP1AXSqY0/HNZ6TCyyYXUuos55upy8kBGhWqCKSl1jjcC5dl5U5fFQbrF+0ke0jzgOi2jgrnBZm/JUwp7fTkpjn0F51KCkHtkryGl1pCdV2h9kcTyByLIKAOH641rC+YE97r9yQbKKMompLyAVZOCJJupU6sM6tTgA6B0WecsBAVxg1pTKP174ZIezC6vuDYwfcZTtSNVE+ZH/9hDkHdJwoCsN+2XplWX3e/QtBj+oxbVIlUEPFMz/4vb+cyLZiQN+i023ZJvcbDD1f69t1luVcdNVj6re6ljZmsZgft0+qFONvN6ji8z2nfjxGYbnmWgXpiLkP4d3VDuHi8zGQTRL586IO//K6+Lkpku32fVo9aKCggjXRv4gdtN9206vJ2MZlf3AJE="
  file: LC1/build/outputs/apk/LC1-release.apk
  skip_cleanup: true
  on:
    repo: eliotstocker/Light-Controller
    tags: true

